# Generated by Django 5.1.7 on 2025-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconnext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_sender', models.CharField()),
                ('request_receiver', models.CharField()),
            ],
        ),
    ]
