# Generated by Django 5.1.7 on 2025-05-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconnext', '0002_friendsrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField()),
                ('friend', models.CharField()),
            ],
        ),
    ]
