# Generated by Django 5.1.7 on 2025-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconnext', '0003_friendlistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicturemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
