# Generated by Django 5.1.7 on 2025-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconnext', '0005_ingredients_receptmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlistmodel',
            name='friend',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='friendlistmodel',
            name='profile',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='friendsrequestmodel',
            name='request_receiver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='friendsrequestmodel',
            name='request_sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilepicturemodel',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
